baseurl = "bennybackslash.github.io/barroomherosite/"
title = "barroomhero"
author = "Ben Doucette"
googleAnalytics = ""
defaultContentLanguage = "en"
language = "en-US"
paginate = 3
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[params]
    description = "barroomhero is a bot for discord."
    favicon = "favicon.ico"
    faviconPng32 = "favicon32.png"
    faviconPng48 = "favicon48.png"
    logo = "logo.png"

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action 
    show = true
    cta = "ACTIVATE"
    link = "https://discordapp.com/api/oauth2/authorize?client_id=689898182427410440&permissions=8&scope=bot" # Relative URL

[params.separator] # Separators between sections on the home page
    show = false

# [params.fa] # Font Awesome options
#    version = "5.7.2"
#    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.form] # Contact form
    netlify = true
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Write something"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.contact] # Contact info
    email = ""
    phone = ""
    skype = ""
    address = ""

[params.social]
    twitter = ""
    facebook = ""
    github = ""
    gitlab = ""
    codepen = ""
    instagram = ""
    pinterest = ""
    youtube = ""
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""

[params.copy] # Copyright
    copy = "" # Empty for default content

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true