baseurl = "https://bennybackslash.github.io/barroomherosite/"
# baseurl = "/"
# relativeURLs = true
uglyURLs = true
title = "barroomhero"
author = "Ben Doucette"
googleAnalytics = ""
defaultContentLanguage = "en"
language = "en-US"
paginate = 3
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[params]
    description = "barroomhero is a bot for discord."
    favicon = "favicon.ico"
    faviconPng32 = "favicon32.png"
    faviconPng48 = "favicon48.png"
    logo = "logo.png"
    background = "background.png"

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action 
    show = true
    cta = "BUY ($1/month)"
    # link = "javascript:void(0)" data-billsby-type="checkout"
    # link = "https://discordapp.com/api/oauth2/authorize?client_id=689898182427410440&permissions=8&scope=bot" # Relative URL

[params.separator] # Separators between sections on the home page
    show = false

